services:
  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 16686:16686

  nats:
    image: nats
    command: --js

  consumer:
    build:
      context: ..
      dockerfile: ./example/cmd/consumer/Dockerfile
    depends_on:
      - nats
      - jaeger

  api:
    build:
      context: ..
      dockerfile: ./example/cmd/rest/Dockerfile
    depends_on:
      - nats
      - jaeger
    ports:
      - 8080:8080
