# https://numtide.github.io/devshell
[[commands]]
package = "go_1_21"

[[commands]]
package = "kind"

[[commands]]
package = "kubernetes-helm"

[[commands]]
package = "fx"

[[commands]]
package = "bombardier"

[[commands]]
package = "natscli"
