services:
  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 16686:16686

  nats:
    image: nats
    command: --js

  consumer-1:
    image: simplebank-consumer:latest
    build:
      context: ../..
      dockerfile: ./examples/simplebank/cmd/consumer/Dockerfile
    environment:
      - CONSUMERS=2
      - CONSUMER_ID=0
    depends_on:
      - nats
      - jaeger

  consumer-2:
    image: simplebank-consumer:latest
    build:
      context: ../..
      dockerfile: ./examples/simplebank/cmd/consumer/Dockerfile
    environment:
      - CONSUMERS=2
      - CONSUMER_ID=1
    depends_on:
      - nats
      - jaeger

  api:
    image: simplebank-api:latest
    build:
      context: ../..
      dockerfile: ./examples/simplebank/cmd/rest/Dockerfile
    environment:
      - CONSUMERS=2
    depends_on:
      - nats
      - jaeger
    ports:
      - 8080:8080
