// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	jetflow "github.com/mathieupost/jetflow"
	mock "github.com/stretchr/testify/mock"
)

// OperatorHandler is an autogenerated mock type for the OperatorHandler type
type OperatorHandler struct {
	mock.Mock
}

type OperatorHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *OperatorHandler) EXPECT() *OperatorHandler_Expecter {
	return &OperatorHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: _a0, _a1, _a2
func (_m *OperatorHandler) Handle(_a0 context.Context, _a1 jetflow.OperatorClient, _a2 *jetflow.Request) ([]byte, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, jetflow.OperatorClient, *jetflow.Request) ([]byte, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, jetflow.OperatorClient, *jetflow.Request) []byte); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, jetflow.OperatorClient, *jetflow.Request) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OperatorHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type OperatorHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 jetflow.OperatorClient
//   - _a2 *jetflow.Request
func (_e *OperatorHandler_Expecter) Handle(_a0 interface{}, _a1 interface{}, _a2 interface{}) *OperatorHandler_Handle_Call {
	return &OperatorHandler_Handle_Call{Call: _e.mock.On("Handle", _a0, _a1, _a2)}
}

func (_c *OperatorHandler_Handle_Call) Run(run func(_a0 context.Context, _a1 jetflow.OperatorClient, _a2 *jetflow.Request)) *OperatorHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(jetflow.OperatorClient), args[2].(*jetflow.Request))
	})
	return _c
}

func (_c *OperatorHandler_Handle_Call) Return(_a0 []byte, _a1 error) *OperatorHandler_Handle_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OperatorHandler_Handle_Call) RunAndReturn(run func(context.Context, jetflow.OperatorClient, *jetflow.Request) ([]byte, error)) *OperatorHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewOperatorHandler creates a new instance of OperatorHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOperatorHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *OperatorHandler {
	mock := &OperatorHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
